name: Master push

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install node modules
        run: yarn
      - name: Test the code
        run: yarn test

  deploy:
    name: Build the Docker container
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Install node modules
        run: yarn
      - name: Build the Docker image
        env:
          DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
          DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
          GITHUB_REGISTRY_USER: ${{ secrets.GITHUB_REGISTRY_USER }}
          GITHUB_REGISTRY_TOKEN: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
        run: yarn build latest && yarn deploy latest
